### ISSUE TITLE
KDE6 build instructions: required packages (Ubuntu)

### ISSUE THREAD

**Issue by jensb** [ScooterSoftware/BCompare-LinuxMenus#11]
Before the KDE6 plugins can build, I needed to install these packages:

```
sudo apt install qt6-base-dev kf6-kcoreaddons-dev kf6-ki18n-dev kf6-kio-dev
```

**Comment by benjarobin** [comment]
Thanks, I added these information to the README in my current pull request #10

**Comment by scootdj** [comment]
@benjarobin fixes merged in 

034b8f36d1f87af8258fda7072c8da26ca0ad5f8
