### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by daveTheOldCoder** [ScooterSoftware/BCompare-LinuxMenus#13]
This link in README.md results in a 404 Not Found:

https://developer.gnome.org/libnautilus-extension

Suggested replacement:

https://github.com/GNOME/nautilus#extensions

**Comment by scootdj** [comment]
Fixed in 

[7eea890](https://github.com/ScooterSoftware/BCompare-LinuxMenus/commit/7eea89080683f104eed69a9934ceabac737c7024)

**Comment by scootdj** [comment]
And thanks for pointing it out
