### ISSUE TITLE
Context menu not working anmymore with Gnome 43

### ISSUE THREAD

**Issue by nicofooo** [ScooterSoftware/BCompare-LinuxMenus#8]
Hello,
with Gnome 43, it seems the extensions for gnome have changed.
So context menu is no more working.

Note: the extension must now been installed in:
->   /usr/lib64/nautilus/extensions-4.0/
instead of
->   /usr/lib64/nautilus/extensions-3.0/
Copying extension foreseen for 3.0 (bcompare-ext-nautilus.$ARCH.so) into 4.0 folder does not work.

**Comment by scooterchris** [comment]
Extensions for Gnome 43 were added in Beyond Compare 4.4.5.

**Comment by scooterchris** [comment]
Extensions for Gnome 43 were added in Beyond Compare 4.4.5.
